package com.zosh.config;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Drops stale MySQL CHECK constraints that were auto-generated by Hibernate
 * when enum columns used ORDINAL mapping.  These constraints conflict now that
 * some enum columns use STRING mapping (e.g. account_status stores
 * "PENDING_ONBOARDING" but the old constraint expects an integer 0-5).
 *
 * Safe to run multiple times — errors are caught and ignored if the
 * constraint no longer exists.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class DatabaseMigrationConfig {

    private final JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void dropStaleCheckConstraints() {

        // seller_chk_1 → account_status between 0 and 5  (ordinal, now STRING)
        dropCheckConstraint("seller", "seller_chk_1");

        // seller_chk_2 → role between 0 and 3
        // role column has no @Enumerated so it uses ORDINAL — constraint is valid,
        // but drop it anyway so Hibernate can re-create it correctly if schema changes.
        dropCheckConstraint("seller", "seller_chk_2");

        log.info("DatabaseMigrationConfig: stale check constraint cleanup complete.");
    }

    private void dropCheckConstraint(String table, String constraintName) {
        try {
            // Check if the constraint exists first
            Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM information_schema.CHECK_CONSTRAINTS " +
                "WHERE CONSTRAINT_SCHEMA = DATABASE() AND CONSTRAINT_NAME = ?",
                Integer.class,
                constraintName
            );

            if (count != null && count > 0) {
                jdbcTemplate.execute(
                    "ALTER TABLE `" + table + "` DROP CHECK `" + constraintName + "`"
                );
                log.info("Dropped stale check constraint '{}' on table '{}'", constraintName, table);
            } else {
                log.debug("Check constraint '{}' not found — already removed.", constraintName);
            }
        } catch (Exception e) {
            // Non-fatal: log and continue startup
            log.warn("Could not drop constraint '{}' on '{}': {}", constraintName, table, e.getMessage());
        }
    }
}
